alias ls='ls -a'
alias ll='ls -al'
alias lh='ls -alh'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias ssh='ssh -2 -4 -o ServerAliveInterval=30 -o ServerAliveCountMax=3'
alias ffmpeg='ffmpeg -hide_banner'
alias ffplay='ffplay -hide_banner'
alias ffprobe='ffprobe -hide_banner'
alias JBcrackR='java -jar /Users/jyxjjj/Downloads/JetBrainsUnlimitedTrial-1.4.jar r'
alias JBcrackU='java -jar /Users/jyxjjj/Downloads/JetBrainsUnlimitedTrial-1.4.jar u'
