export LLAMA_ARG_UBATCH=1
export LLAMA_ARG_MLOCK=1
export LLAMA_ARG_MMAP=1
export LLAMA_ARG_CACHE_TYPE_K=f16
export LLAMA_ARG_CACHE_TYPE_V=f16
export LLAMA_MODELS_MAX=1
export LLAMA_ARG_N_PARALLEL=1
export LLAMA_ARG_HOST=127.0.0.1
export LLAMA_ARG_PORT=11434
alias llama-cli='llama-cli --temp 0.1'
alias llama-server='llama-server --temp 0.1'
