no-emit-version
personal-digest-preferences SHA512
cert-digest-algo SHA512
default-preference-list SHA512 SHA256 AES256 AES ZLIB ZIP Uncompressed
personal-cipher-preferences AES
default-key C9F1DE0C765B4E98EACF0D81AD0957666145F8C0
auto-key-retrieve
trust-model pgp
